### ISSUE TITLE
[Feature Request] Add more information about files being scanned

### ISSUE THREAD

**Issue by SilasLaspada** [mnadareski/BurnOutSharp#10]
Partially to be more informative, partially to make it more clear that the program is still running and hasn't crashed, BOS should give more output about the files currently being scanned, such as saying what part of an archive is being scanned or the like.

**Comment by mnadareski** [comment]
Just confirming that I see this and acknowledge that scanning *within* archives is not exactly well determined right now.

**Comment by mnadareski** [comment]
Progress indicators for in-archive scans have been implemented some time ago now. Can't find the appopriate commits to link here, though.
