### ISSUE TITLE
[New Protection?] Validate Key Xtra SubModule

### ISSUE THREAD

**Issue by Flashfire42** [mnadareski/BurnOutSharp#108]
IS LIKELY A FALSE POSITIVE FURTHER TESTS AND SAMPLES NEEDED
17:07:42 | E:\PHEAD\xtras\budapi.x32 | Validate Key Xtra SubModule
VirusTotal Link
https://www.virustotal.com/gui/file/fa8334bdc13fc238c6d94f85ff48f7e4eb50172bf2339527d1daa6bf4f2f5ab8
MD5:	7ca9a5b38a26dabc825ca65e47277ab0
SHA-1:	c06acd186dbd63109f1007a1dfe5a826015d063b
SHA-256:	fa8334bdc13fc238c6d94f85ff48f7e4eb50172bf2339527d1daa6bf4f2f5ab8

**Comment by n0samu** [comment]
I verified that neither the budapi.x32 (Buddy API) library nor the game's executable depend on any Validate Key Xtra. My conclusion is that ProtectionID has a faulty signature for the Validate Key Xtra protection. Buddy API and Validate Key Xtra are two entirely separate Xtras; one does not depend on the other, and games can use one without using the other.
