### ISSUE TITLE
7-Zip SFX Setup Module

### ISSUE THREAD

**Issue by Flashfire42** [mnadareski/BurnOutSharp#109]
18:46:43 | D:\Testing\1Old Copied Discs\Testing For BOS\Protection Samples\7-Zip SFX Setup Module\basilisk-latest.win64.installer.exe | 7-Zip SFX Setup Module
VirusTotal Link
https://www.virustotal.com/gui/file/9e0546951d2642c8cb0050726ad5c51e165b8f5c7f84fa9f0d7e5c01ffe70b65/details
MD5:	165fe0d2723692a66791717dbd1381d9
SHA-1:	a6b9f4514469e4d2fdce1e57f08975c384c4aac8
SHA-256:	9e0546951d2642c8cb0050726ad5c51e165b8f5c7f84fa9f0d7e5c01ffe70b65

**Comment by Flashfire42** [comment]
This sample also detects InstallAware Setup Module
https://www.virustotal.com/gui/file/99834bc65621cea6ff004761d003d07ba269f5ac2b24be8fa3ae3d1686f08099/details

**Comment by SilasLaspada** [comment]
The current version of 7-zip is able to create an exe that is detected as "7-Zip SFX Setup Module" by PiD easily by just creating an archive, selecting 7z as the format, and checking the "Create SFX archive" box.

**Comment by Flashfire42** [comment]
There are a few 7zip SFX that are not detected however this is known and is being looked into. in the mean time with this packer now being supported I will be closing this issue
