### ISSUE TITLE
Possible false positive for Key2Audio XS on an XCP2 CD

### ISSUE THREAD

**Issue by SilasLaspada** [mnadareski/BurnOutSharp#13]
On a CD confirmed to have XCP2, BOS detects some files as Key2Audio XS, which I would consider to be very unlikely to be on the same CD. The suspected false positives are:
E:\BIN\WIN32\SDKHM.DLL: Key2Audio XS
E:\BIN\WIN32\SDKHM.EXE: Key2Audio XS

**Comment by mnadareski** [comment]
Those are actually the only files that Key2Audio XS checks for. I honestly don't know what that protection is supposed to be, given that they originated from the BurnOut original version. If you can confirm that those are *not* indicative of Key2Audio XS, I'd appreciate it.

**Comment by mnadareski** [comment]
After chatting about this elsewhere, it seems like these might not be false positives after all. I will leave this open because honestly, the conclusion we came to wasn't that conclusive, but it's probably right given the evidence we have.

**Comment by SilasLaspada** [comment]
Fixed by 8502924083b6a5cd6e04ef8a72f83bf3a4490a13.
