### ISSUE TITLE
[Bug] MediaMax CD-3 False Positive

### ISSUE THREAD

**Issue by NovaSAurora** [mnadareski/BurnOutSharp#134]
![image](https://user-images.githubusercontent.com/68273043/180491427-48ca363e-397f-4122-9be0-0998319033f8.png)

**Comment by mnadareski** [comment]
Fixed by https://github.com/mnadareski/BurnOutSharp/commit/8a419f50db8a6124b8dd72fd4fcf7534e6c06969
