### ISSUE TITLE
Add support for extracting WinZip SFX archives

### ISSUE THREAD

**Issue by SilasLaspada** [mnadareski/BurnOutSharp#19]
Title says it all, will do more research later to see if any usable libraries can do that right now.

**Comment by SilasLaspada** [comment]
Also add support for Microsoft SFX Cab if it's any different.

**Comment by SilasLaspada** [comment]
Can be closed, unless you want to wait to implement Microsoft SFX Cab too before closing.

**Comment by mnadareski** [comment]
Fixed by https://github.com/mnadareski/BurnOutSharp/commit/a39ae9facfd581a8d9daed893d72a9a87b2fd722
