### ISSUE TITLE
[Protection] Microsoft Playfab

### ISSUE THREAD

**Issue by Flashfire42** [mnadareski/BurnOutSharp#202]
https://store.steampowered.com/app/1428140/Riding_Seas/
Incorporates 3rd-party DRM: Microsoft Playfab

**Comment by Zopolis4** [comment]
A variety of games are listed [here](https://azure.microsoft.com/en-us/products/playfab/#overview) as well under `Games that run on PlayFab`.

**Comment by TheRogueArchivist** [comment]
Duplicate of #200.
