### ISSUE TITLE
Possible Ring PROTECH False Positive

### ISSUE THREAD

**Issue by NovaSAurora** [mnadareski/BurnOutSharp#22]
Dumping "Brut@l" DVD game detects Ring PROTECH, PiD does not detect anything.

**Comment by mnadareski** [comment]
No real knowledge out there about the inner workings. As far as I know, the code here is an adaptation of the original BurnOut code, so this will take some time to look into. The only other info is here: https://www.cdmediaworld.com/hardware/cdrom/cd_protections_ring_protech.shtml
