### ISSUE TITLE
Relicense to MIT

### ISSUE THREAD

**Issue by mnadareski** [mnadareski/BurnOutSharp#225]
We need to have a quorum of people who have contributed that their contributions can be relicensed from the current GNU GPL 3 license to a more permissive one, specifically MIT.

The following contributors need to give their explicit approval that their code contributions can be relicensed:
- @mnadareski - I give consent to relicensing by default
- @TheRogueArchivist

**Comment by TheRogueArchivist** [comment]
I agree to relicensing to MIT.

**Comment by mnadareski** [comment]
We have a quorum among the contributors. We have chosen to relicense all existing and future code as MIT.
