### ISSUE TITLE
'Destination array is not long enough to copy all the items in the collection. Check array index and length.' in DirectX9 Redist

### ISSUE THREAD

**Issue by TheRogueArchivist** [mnadareski/BurnOutSharp#250]
The exception 'Destination array is not long enough to copy all the items in the collection. Check array index and length.' occurs in a DirectX9 redistributable file "microsoft.directx.directplay.dll" inside the CAB file "Apr2006_MDX1_x86.cab". The file scans without any exceptions if it's been extracted from the CAB before scanning using Windows Explorer, but still throws an exception if it's been extracted with BOS.

**Comment by mnadareski** [comment]
Duplicate of https://github.com/mnadareski/BurnOutSharp/issues/243
