### ISSUE TITLE
StackOverflowException while scanning "psisdecd.dll" in DirectX9 Redistributable

### ISSUE THREAD

**Issue by TheRogueArchivist** [mnadareski/BurnOutSharp#253]
BOS crashes with a System.StackOverflowException while scanning the file "psisdecd.dll" in a DirectX9 Redistributable. As this is from a redistributable, I've included a zipped copy of the cab that contains this file.
[BDA.zip](https://github.com/mnadareski/BurnOutSharp/files/11472643/BDA.zip)

**Comment by mnadareski** [comment]
Duplicate of https://github.com/mnadareski/BurnOutSharp/issues/243
