### ISSUE TITLE
[Bug?] Weird magical mysterious crashes during scanning

### ISSUE THREAD

**Issue by NovaSAurora** [mnadareski/BurnOutSharp#54]
https://media.discordapp.net/attachments/461797735427735562/876235551248904243/unknown.png

Hell if I know what's going on

**Comment by mnadareski** [comment]
@NovaSAurora have you run into this error at all on the same discs? A lot has changed this past month.

**Comment by mnadareski** [comment]
Can't reproduce, closing.
