### ISSUE TITLE
[Packer] Add ASPack/ASProtect detection

### ISSUE THREAD

**Issue by SilasLaspada** [mnadareski/BurnOutSharp#74]
Both packers are actually still around today, though the new version of ASProtect seems to referred to as ASProtect 32/64. ASProtect 2.x seems to be referred to as ASProtect SKE, with either one version in common use, or PiD's version detection lacking. ASPack still seems to be available under the same name, ASPack identification should be relatively easy, as I see "aspack" inside of the header of the samples I've seen. I haven't seen that string, nor any equivalent, in ASProtect. This makes sense, since ASPack seems to be advertised as a more budget friendly packer that doesn't have as much emphasis on security. I assume ASProtect is essentially a form of ASPack+Security, but that's just a guess.

Official site: http://www.aspack.com/
ASPack unpacker: https://gist.github.com/abhisek/3659931
ASProtect RE: https://github.com/pstolarz/asprext

**Comment by mnadareski** [comment]
https://unprotect.it/technique/aspack/

**Comment by mnadareski** [comment]
Implemented in https://github.com/mnadareski/BurnOutSharp/commit/8fb42bc12d94521559c961275897ba81b64336c0
