### ISSUE TITLE
[Removal Request] Key-Lock detection

### ISSUE THREAD

**Issue by SilasLaspada** [mnadareski/BurnOutSharp#83]
I believe Key-Lock detection should be removed, due to the difficulty in finding samples, as well as the likely legal implications that acquiring samples would have as Key-Lock seems primarily intended to protect internal enterprise software, and the company and product are both currently still around.

**Comment by mnadareski** [comment]
This has not been removed, instead gated behind the debug flag as with other unverified protections.
