### ISSUE TITLE
[Enhancement] TAGES driver detection

### ISSUE THREAD

**Issue by SilasLaspada** [mnadareski/BurnOutSharp#84]
TAGES appears to have certain drivers that are currently undetected by BOS. Information on them is sparse online, but https://forum.daemon-tools.cc/forum/foreign-languages/german-section/3542-/page2?t=3457&page=2 and PiD both seem to indicate that the following files indicate the presence of TAGES. I can personally confirm some form of copy protection is present on a disc containing these drivers, but I'm unable to personally confirm whether or not it is TAGES.

/Drivers/Silent.exe
/Drivers/9x/hwpsgt.vxd
/Drivers/9x/lemsgt.vxd
/Drivers/NT/hwpsgt.sys
/Drivers/NT/lemsgt.sys

**Comment by mnadareski** [comment]
Fixed by https://github.com/mnadareski/BurnOutSharp/commit/30c249ce74f3f357a023a53be75253ec3cb315cb
