### ISSUE TITLE
[Packer] Shrinker

### ISSUE THREAD

**Issue by Flashfire42** [mnadareski/BurnOutSharp#94]
"D:\Testing\1Old Copied Discs\1000GAMES\ACTION\Axellus\Setup.exe" Detected as Shrinker 3.4
VirusTotal Link
https://www.virustotal.com/gui/file/7ac63ac4ba0df698af015d80dff69434f1d15fd9fca5b05259c1fa9c7812f41e/details
MD5:	78ed67bd3cb8def97e3530870f54845d
SHA-1:	0a10d86b1244201243772f4c9c7194fbc526b719
SHA-256:	7ac63ac4ba0df698af015d80dff69434f1d15fd9fca5b05259c1fa9c7812f41e

**Comment by mnadareski** [comment]
Fixed by https://github.com/mnadareski/BurnOutSharp/commit/cab200e89333d91a82bc302bbca43e7ca45d666a
