### ISSUE TITLE
Exception Opening File

### ISSUE THREAD

**Issue by Flashfire42** [mnadareski/BurnOutSharp#95]
D:\Testing\1Old Copied Discs\1000GAMES\BOARD\MJWIN\PCX2TIS.EXE: [Exception opening file, please try again]
VirusTotal Link
https://www.virustotal.com/gui/file/2242b41072e53b25159bbc5d12ca8b38cc530e40c44ec18b9156b2c936d99bb2/details
MD5:	508053a2860a6e4874b39814eba145b7
SHA-1:	9bb8c960c8a25cf73a27fc468f450ccb9d103c3a
SHA-256:	2242b41072e53b25159bbc5d12ca8b38cc530e40c44ec18b9156b2c936d99bb2
Running Latest test build of BurnOutSharp text.exe with CRC32 of FD314ED9
Unsure of what went wrong sorry I can't be of more help. If you need the file don't hesitate to contact me

**Comment by mnadareski** [comment]
Fixed at some arbitrary point in the past 50 commits.
